name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler: '2.4.10'
        bundler-cache: true
    - name: Build website
      env:
        JEKYLL_ENV: production
      run: bundle exec jekyll build

  deploy:
    if: github.event_name == 'push'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler: '2.4.10'
        bundler-cache: true
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT
    - name: Deploy website
      run: |
        yes | bash bin/deploy --verbose \
          --src ${{ steps.setup.outputs.SRC_BRANCH }} \
          --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
